baseURL = 'http://example.org/'
languageCode = 'sv-SE'
defaultContentLanguage = 'sv'
defaultContentLang = 'sv'
title = 'Gnistor'
buildFuture = true
[taxonomies]
	location = 'locations'
	form = 'forms'
[sitemap]
	changefreq = 'always'
	filename = 'sitemap.xml'
	priority = 0.5
[outputFormats]
[outputFormats.mp3feed]
	mediatype = "application/rss+xml"
	path = "/feed/mp3"
[outputs]
	home = [ "HTML", "RSS", "mp3feed" ]
[params]
[params.author]
	name = 'Gnistor'
	email = 'hej@gnistor.se'
[params.podcast]
	description = '<podcast description>'
	tagline = 'Foodie Flashback - Food & Memories'
	download_url = 'https://media.gnistor.se/'
	cdn_url = 'https://media.gnistor.se/'
	itunes_url = 'https://podcasts.apple.com/us/podcast/foodie-flashback/id1504783815'
	itunes_id = 'id1504783815'